allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: false
  sharp: false
  unrs-resolver: false
patchedDependencies:
  '@keystatic/core@0.6.9': patches/@keystatic__core@0.6.9.patch
